// tools/ai-startup-fix-agent/fixes/fixAuthSetup.js

import fs from "fs";

export function generateFixAuthSetupPatch() {
    return `
// AUTO-GENERATED BY AI STARTUP FIX AGENT
// Repariert fehlende storageState.json

import { test as setup, expect } from "@playwright/test";

setup("authenticate", async ({ page }) => {
  await page.goto(process.env.BASE_URL + "/login");

  await page.fill('input[name="username"]', process.env.E2E_USER);
  await page.fill('input[name="password"]', process.env.E2E_PASSWORD);
  await page.click('button[type="submit"]');

  await page.waitForURL("**/dashboard");

  await page.context().storageState({ path: "storageState.json" });
});
`;
}

export function applyFixAuthSetup(filePath) {
    const patch = generateFixAuthSetupPatch();
    fs.writeFileSync(filePath, patch, "utf8");
    console.log("✅ auth.setup.ts erfolgreich repariert.");
    return true;
}
