// tools/ai-startup-fix-agent/fixes/fixDbEnvVariables.js

import fs from "fs";

export function generateFixDbEnvPatch() {
    return `
# AUTO-GENERATED BY AI STARTUP FIX AGENT
# Korrigiert falsche DB-Variablen

env:
  SYS_DB_NAME: praxi
  SYS_DB_USER: praxi
  SYS_DB_PASSWORD: praxi
  SYS_DB_HOST: 127.0.0.1
  SYS_DB_PORT: 5432
`;
}

export function applyFixDbEnvVariables(workflowPath) {
    const patch = generateFixDbEnvPatch();
    const content = fs.readFileSync(workflowPath, "utf8");

    if (content.includes("SYS_DB_NAME")) {
        console.log("⚠️  DB-ENV-Patch bereits vorhanden.");
        return false;
    }

    fs.writeFileSync(workflowPath, content + "\n" + patch);
    console.log("✅ DB-ENV-Variablen erfolgreich korrigiert.");
    return true;
}
