// tools/ai-startup-fix-agent/fixes/fixDjangoSettings.js

import fs from "fs";

export function generateFixDjangoSettingsPatch() {
    return `
# AUTO-GENERATED BY AI STARTUP FIX AGENT
# Repariert DJANGO_SETTINGS_MODULE

env:
  DJANGO_SETTINGS_MODULE: praxi_backend.settings.dev
`;
}

export function applyFixDjangoSettings(workflowPath) {
    const patch = generateFixDjangoSettingsPatch();
    const content = fs.readFileSync(workflowPath, "utf8");

    if (content.includes("DJANGO_SETTINGS_MODULE")) {
        console.log("⚠️  Django-Settings bereits gesetzt.");
        return false;
    }

    fs.writeFileSync(workflowPath, content + "\n" + patch);
    console.log("✅ Django-Settings erfolgreich repariert.");
    return true;
}
