# Generated by Django 5.2.10 on 2026-01-20 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_alter_appointmentresource_id_alter_operation_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-start_time', '-id'], 'verbose_name': 'Termin', 'verbose_name_plural': 'Termine'},
        ),
        migrations.AlterModelOptions(
            name='appointmentresource',
            options={'ordering': ['appointment_id', 'resource_id', 'id'], 'verbose_name': 'Termin-Ressource', 'verbose_name_plural': 'Termin-Ressourcen'},
        ),
        migrations.AlterModelOptions(
            name='doctorabsence',
            options={'ordering': ['doctor_id', 'start_date', 'end_date', 'id'], 'verbose_name': 'Abwesenheit', 'verbose_name_plural': 'Abwesenheiten'},
        ),
        migrations.AlterModelOptions(
            name='doctorbreak',
            options={'ordering': ['date', 'start_time', 'doctor_id', 'id'], 'verbose_name': 'Pause', 'verbose_name_plural': 'Pausen'},
        ),
        migrations.AlterModelOptions(
            name='doctorhours',
            options={'ordering': ['doctor_id', 'weekday', 'start_time', 'id'], 'verbose_name': 'Arbeitszeit', 'verbose_name_plural': 'Arbeitszeiten'},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['-start_time', '-id'], 'verbose_name': 'Operation', 'verbose_name_plural': 'Operationen'},
        ),
        migrations.AlterModelOptions(
            name='operationdevice',
            options={'ordering': ['operation_id', 'resource_id', 'id'], 'verbose_name': 'OP-Gerät', 'verbose_name_plural': 'OP-Geräte'},
        ),
        migrations.AlterModelOptions(
            name='operationtype',
            options={'ordering': ['name', 'id'], 'verbose_name': 'OP-Typ', 'verbose_name_plural': 'OP-Typen'},
        ),
        migrations.AlterModelOptions(
            name='patientflow',
            options={'ordering': ['-status_changed_at', '-id'], 'verbose_name': 'Patientenfluss', 'verbose_name_plural': 'Patientenflüsse'},
        ),
        migrations.AlterModelOptions(
            name='practicehours',
            options={'ordering': ['weekday', 'start_time', 'id'], 'verbose_name': 'Praxisöffnungszeit', 'verbose_name_plural': 'Praxisöffnungszeiten'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['type', 'name', 'id'], 'verbose_name': 'Ressource', 'verbose_name_plural': 'Ressourcen'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Arzt'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(verbose_name='Endzeit'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notizen'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_id',
            field=models.IntegerField(verbose_name='Patient-ID'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='appointments', through='appointments.AppointmentResource', to='appointments.resource', verbose_name='Ressourcen'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(verbose_name='Startzeit'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled'), ('completed', 'completed')], default='scheduled', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointmenttype', verbose_name='Terminart'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='appointmentresource',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_resources', to='appointments.appointment', verbose_name='Termin'),
        ),
        migrations.AlterField(
            model_name='appointmentresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_resources', to='appointments.resource', verbose_name='Ressource'),
        ),
        migrations.AlterField(
            model_name='appointmenttype',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='appointmenttype',
            name='color',
            field=models.CharField(blank=True, default='#2E8B57', max_length=7, null=True, verbose_name='Farbe'),
        ),
        migrations.AlterField(
            model_name='appointmenttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='appointmenttype',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dauer (Minuten)'),
        ),
        migrations.AlterField(
            model_name='appointmenttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='appointmenttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='doctorabsence',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='doctorabsence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='doctorabsence',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_absences', to=settings.AUTH_USER_MODEL, verbose_name='Arzt'),
        ),
        migrations.AlterField(
            model_name='doctorabsence',
            name='end_date',
            field=models.DateField(verbose_name='Enddatum'),
        ),
        migrations.AlterField(
            model_name='doctorabsence',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Grund'),
        ),
        migrations.AlterField(
            model_name='doctorabsence',
            name='start_date',
            field=models.DateField(verbose_name='Startdatum'),
        ),
        migrations.AlterField(
            model_name='doctorabsence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='doctorbreak',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='doctorbreak',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='doctorbreak',
            name='date',
            field=models.DateField(verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='doctorbreak',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_breaks', to=settings.AUTH_USER_MODEL, verbose_name='Arzt'),
        ),
        migrations.AlterField(
            model_name='doctorbreak',
            name='end_time',
            field=models.TimeField(verbose_name='Endzeit'),
        ),
        migrations.AlterField(
            model_name='doctorbreak',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Grund'),
        ),
        migrations.AlterField(
            model_name='doctorbreak',
            name='start_time',
            field=models.TimeField(verbose_name='Startzeit'),
        ),
        migrations.AlterField(
            model_name='doctorbreak',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='doctorhours',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='doctorhours',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='doctorhours',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_hours', to=settings.AUTH_USER_MODEL, verbose_name='Arzt'),
        ),
        migrations.AlterField(
            model_name='doctorhours',
            name='end_time',
            field=models.TimeField(verbose_name='Endzeit'),
        ),
        migrations.AlterField(
            model_name='doctorhours',
            name='start_time',
            field=models.TimeField(verbose_name='Startzeit'),
        ),
        migrations.AlterField(
            model_name='doctorhours',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='doctorhours',
            name='weekday',
            field=models.IntegerField(verbose_name='Wochentag'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='anesthesist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='op_anesthesist', to=settings.AUTH_USER_MODEL, verbose_name='Anästhesist'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='op_assistant', to=settings.AUTH_USER_MODEL, verbose_name='Assistent'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='end_time',
            field=models.DateTimeField(verbose_name='Endzeit'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notizen'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='op_devices',
            field=models.ManyToManyField(blank=True, related_name='operations_as_device', through='appointments.OperationDevice', to='appointments.resource', verbose_name='OP-Geräte'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='op_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_as_room', to='appointments.resource', verbose_name='OP-Raum'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='op_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.operationtype', verbose_name='OP-Typ'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='patient_id',
            field=models.IntegerField(verbose_name='Patient-ID'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='primary_surgeon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op_primary', to=settings.AUTH_USER_MODEL, verbose_name='Hauptoperateur'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='start_time',
            field=models.DateTimeField(verbose_name='Startzeit'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('planned', 'planned'), ('confirmed', 'confirmed'), ('running', 'running'), ('done', 'done'), ('cancelled', 'cancelled')], default='planned', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='operationdevice',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_devices', to='appointments.operation', verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='operationdevice',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_devices', to='appointments.resource', verbose_name='Ressource'),
        ),
        migrations.AlterField(
            model_name='operationtype',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='operationtype',
            name='color',
            field=models.CharField(default='#8A2BE2', max_length=7, verbose_name='Farbe'),
        ),
        migrations.AlterField(
            model_name='operationtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='operationtype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='operationtype',
            name='op_duration',
            field=models.IntegerField(default=0, verbose_name='OP-Dauer (Minuten)'),
        ),
        migrations.AlterField(
            model_name='operationtype',
            name='post_duration',
            field=models.IntegerField(default=0, verbose_name='Nachbereitungsdauer (Minuten)'),
        ),
        migrations.AlterField(
            model_name='operationtype',
            name='prep_duration',
            field=models.IntegerField(default=0, verbose_name='Vorbereitungsdauer (Minuten)'),
        ),
        migrations.AlterField(
            model_name='operationtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='patientflow',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_flows', to='appointments.appointment', verbose_name='Termin'),
        ),
        migrations.AlterField(
            model_name='patientflow',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ankunftszeit'),
        ),
        migrations.AlterField(
            model_name='patientflow',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notizen'),
        ),
        migrations.AlterField(
            model_name='patientflow',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_flows', to='appointments.operation', verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='patientflow',
            name='status',
            field=models.CharField(choices=[('registered', 'registered'), ('waiting', 'waiting'), ('preparing', 'preparing'), ('in_treatment', 'in_treatment'), ('post_treatment', 'post_treatment'), ('done', 'done')], default='registered', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='patientflow',
            name='status_changed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Status geändert am'),
        ),
        migrations.AlterField(
            model_name='practicehours',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='practicehours',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='practicehours',
            name='end_time',
            field=models.TimeField(verbose_name='Endzeit'),
        ),
        migrations.AlterField(
            model_name='practicehours',
            name='start_time',
            field=models.TimeField(verbose_name='Startzeit'),
        ),
        migrations.AlterField(
            model_name='practicehours',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='practicehours',
            name='weekday',
            field=models.IntegerField(verbose_name='Wochentag'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='color',
            field=models.CharField(default='#6A5ACD', max_length=7, verbose_name='Farbe'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('room', 'room'), ('device', 'device')], max_length=20, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
    ]
