BEGIN;
SELECT setval(pg_get_serial_sequence('"core_role"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "core_role";
SELECT setval(pg_get_serial_sequence('"core_user_groups"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "core_user_groups";
SELECT setval(pg_get_serial_sequence('"core_user_user_permissions"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "core_user_user_permissions";
SELECT setval(pg_get_serial_sequence('"core_user"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "core_user";
SELECT setval(pg_get_serial_sequence('"core_auditlog"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "core_auditlog";
SELECT setval(pg_get_serial_sequence('"appointments_appointmenttype"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "appointments_appointmenttype";
SELECT setval(pg_get_serial_sequence('"appointments_practicehours"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "appointments_practicehours";
SELECT setval(pg_get_serial_sequence('"appointments_doctorhours"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "appointments_doctorhours";
SELECT setval(pg_get_serial_sequence('"appointments_doctorabsence"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "appointments_doctorabsence";
SELECT setval(pg_get_serial_sequence('"appointments_doctorbreak"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "appointments_doctorbreak";
SELECT setval(pg_get_serial_sequence('"appointments_appointment"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "appointments_appointment";
SELECT setval(pg_get_serial_sequence('"appointments_resource"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "appointments_resource";
SELECT setval(pg_get_serial_sequence('"appointments_appointmentresource"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "appointments_appointmentresource";
SELECT setval(pg_get_serial_sequence('"appointments_operationtype"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "appointments_operationtype";
SELECT setval(pg_get_serial_sequence('"appointments_operation"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "appointments_operation";
SELECT setval(pg_get_serial_sequence('"appointments_operationdevice"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "appointments_operationdevice";
SELECT setval(pg_get_serial_sequence('"appointments_patientflow"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "appointments_patientflow";
SELECT setval(pg_get_serial_sequence('"patient_documents"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "patient_documents";
SELECT setval(pg_get_serial_sequence('"patient_notes"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "patient_notes";
SELECT setval(pg_get_serial_sequence('"patients_cache"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "patients_cache";
COMMIT;
